# Generated by Django 5.1.4 on 2025-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(blank=None, default='0', max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('uni', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hub',
            old_name='driver',
            new_name='driver_fullname',
        ),
        migrations.RenameField(
            model_name='hub',
            old_name='where_to',
            new_name='driver_gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uni',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uni_id',
        ),
        migrations.AddField(
            model_name='hub',
            name='driver_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hub',
            name='driver_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='is_availiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uni',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
