# Generated by Django 5.1.4 on 2025-05-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0002_student_rename_driver_hub_driver_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='school_name_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uni_id',
        ),
        migrations.AddField(
            model_name='hub',
            name='uni',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.uni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.uni'),
            preserve_default=False,
        ),
    ]
