# Generated by Django 5.1.4 on 2025-05-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0003_remove_hub_school_name_id_remove_student_uni_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.uni'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.uni'),
        ),
    ]
