# Generated by Django 5.1.4 on 2025-05-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0004_alter_hub_uni_alter_student_uni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='location',
        ),
    ]
