# Generated by Django 5.1.4 on 2025-05-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0006_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='student_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.hub'),
        ),
        migrations.AddField(
            model_name='ride',
            name='student',
            field=models.ManyToManyField(blank=True, to='school_transit_app.student'),
        ),
        migrations.AddField(
            model_name='ride',
            name='uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_transit_app.uni'),
        ),
    ]
