# Generated by Django 5.1.4 on 2025-05-16 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0011_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='user',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='transit_status',
            field=models.CharField(choices=[('mady', 'ride requested'), ('nuke', 'ride is on the way'), ('speedy', 'ride in transit'), ('zeus', 'ride complete')], default='NA', max_length=225),
        ),
    ]
