# Generated by Django 5.1.4 on 2025-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_transit_app', '0012_hub_user_alter_ride_transit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='review_comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='seater',
            field=models.CharField(choices=[('one', 'one seater'), ('two', 'two seater')], default='one', max_length=225),
        ),
        migrations.AddField(
            model_name='ride',
            name='wait_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
